name: Project Publish
on:
  pull_request:
    types: [closed]
    branches:    
      - master
env:
  module: datetime
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    if: ${{ startsWith(gitea.event.pull_request.labels[0].name, 'Project/Release') && gitea.event.pull_request.milestone != null && gitea.event.pull_request.merged == true }}
    steps:
      - 
        name: Checkout
        uses: tiagomta/checkout@v1
        with:
          repository: vistta/vistta
          ref: ${{ gitea.event.pull_request.head.ref }}
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0
          submodules: true
      - 
        name: Publish Package (Gitea)
        uses: tiagomta/npm@v1
        with:
          command: publish --scope vistta --registry https://git.vistta.org/api/packages/vistta/npm/
          working-directory: ./packages/${{ env.module }}
          token: ${{ secrets.GIT_TOKEN }}
      - 
        name: Publish Package (NPM)
        uses: tiagomta/npm@v1
        with:
          command: publish --scope vistta
          working-directory: ./packages/${{ env.module }}
          token: ${{ secrets.NPM_TOKEN }}
      - 
        name: Tag
        id: tag
        uses: tiagomta/npm@v1
        with:
          command: version tag --email devops@vistta.org --force
          working-directory: ./packages/${{ env.module }}
      - 
        name: Close Milestone
        uses: tiagomta/gitea@v1
        with:
          command: milestone close ${{ gitea.event.pull_request.milestone.id }}
      - 
        name: Create Release
        uses: tiagomta/gitea@v1
        with:
          command: release create ${{ steps.tag.outputs.result }}