name: Project Validation
on:
  pull_request:
    types: [synchronize]
    branches:    
      - master
jobs:
  validation:
    uses: vistta/workflows/validation.yml@master
    with:
      directory: ./packages/datetime