name: Project Validation
on:
  pull_request:
    types: [synchronize]
    branches:    
      - master
jobs:
  validation:
    uses: ./.gitea/workflows/validation
    with:
      directory: ./packages/datetime