name: Project Validation
on:
  pull_request:
    types: [synchronize]
    branches:    
      - master
jobs:
  validation:
    uses: ./.gitea/templates/validation.yml
      env:
        PACKAGE_NAME: datetime