name: Project Validation
on:
  pull_request:
    types: [synchronize]
    branches:    
      - master
jobs:
  Validation:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: /.gitea/templates/validation.yml
        env:
          PACKAGE_NAME: datetime